name: Articles Branch CI

on:
  push:
    branches: ["articles/**"]
  pull_request:
    branches: ["articles/**"]

jobs:
  make-article:
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/typst/typst:latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup environment
        run: |
          apk add make bash
          make setup

      - name: get branch info
        id: branch_info
        shell: bash
        run: |
          BRANCH="${GITHUB_REF#refs/heads/}"
          echo "branch=$BRANCH" >> $GITHUB_OUTPUT
          if [[ "$BRANCH" =~ ^articles/([^/]+)$ ]]; then
            ARTICLE_NAME="${BASH_REMATCH[1]}"
            echo "match=true" >> $GITHUB_OUTPUT
            echo "article_name=$ARTICLE_NAME" >> $GITHUB_OUTPUT
          fi

      - name: compile article
        if: steps.branch_info.outputs.match
        run: |
          cd "${{ steps.branch_info.outputs.branch }}"
          make compile

      - name: upload artifact
        if: steps.branch_info.outputs.match
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.branch_info.outputs.article_name }}.pdf
          path: ${{ steps.branch_info.outputs.branch }}/main.pdf
          retention-days: 3
